create table "public"."children" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."children" enable row level security;

create table "public"."covid_vaccine" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."covid_vaccine" enable row level security;

create table "public"."ethnicities" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."ethnicities" enable row level security;

create table "public"."family_plans" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."family_plans" enable row level security;

create table "public"."genders" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "plural_name" text
);


alter table "public"."genders" enable row level security;

create table "public"."interaction_status" (
    "id" integer generated by default as identity not null,
    "status" text not null
);


alter table "public"."interaction_status" enable row level security;

create table "public"."interactions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "updated_by" uuid not null,
    "actor_id" uuid not null,
    "target_id" uuid not null,
    "status_id" integer not null,
    "answer_id" uuid,
    "photo_id" uuid
);


alter table "public"."interactions" enable row level security;

create table "public"."pets" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."pets" enable row level security;

create table "public"."profile_answers" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "prompt_id" integer not null,
    "answer_text" text not null,
    "answer_order" integer not null,
    "is_active" boolean
);


alter table "public"."profile_answers" enable row level security;

create table "public"."profile_ethnicities" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
);


alter table "public"."profile_ethnicities" enable row level security;

create table "public"."profile_ethnicity_preferences" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
);


alter table "public"."profile_ethnicity_preferences" enable row level security;

create table "public"."profile_gender_preferences" (
    "profile_id" uuid not null,
    "gender_id" integer not null
);


alter table "public"."profile_gender_preferences" enable row level security;

create table "public"."profile_pets" (
    "profile_id" uuid not null,
    "pet_id" integer not null
);


alter table "public"."profile_pets" enable row level security;

create table "public"."profile_photos" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "photo_url" text not null,
    "photo_order" integer not null,
    "is_active" boolean not null
);


alter table "public"."profile_photos" enable row level security;

create table "public"."profile_pronouns" (
    "profile_id" uuid not null,
    "pronoun_id" integer not null
);


alter table "public"."profile_pronouns" enable row level security;

create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "dob" date,
    "height_cm" integer,
    "neighborhood" text,
    "latitude" double precision,
    "longitude" double precision,
    "children_id" integer,
    "family_plan_id" integer,
    "covid_vaccine_id" integer,
    "zodiac_sign_id" integer,
    "gender_id" integer,
    "sexuality_id" integer,
    "max_distance_km" integer default 160,
    "min_age" integer default 18,
    "max_age" integer default 80,
    "phone" text,
    "user_id" uuid
);


alter table "public"."profiles" enable row level security;

create table "public"."prompts" (
    "id" integer generated by default as identity not null,
    "question" text not null
);


alter table "public"."prompts" enable row level security;

create table "public"."pronouns" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."pronouns" enable row level security;

create table "public"."sexualities" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."sexualities" enable row level security;

create table "public"."zodiac_signs" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."zodiac_signs" enable row level security;

CREATE UNIQUE INDEX children_pkey ON public.children USING btree (id);

CREATE UNIQUE INDEX covid_vaccine_pkey ON public.covid_vaccine USING btree (id);

CREATE UNIQUE INDEX ethnicities_pkey ON public.ethnicities USING btree (id);

CREATE UNIQUE INDEX family_plans_pkey ON public.family_plans USING btree (id);

CREATE UNIQUE INDEX genders_pkey ON public.genders USING btree (id);

CREATE UNIQUE INDEX interaction_status_pkey ON public.interaction_status USING btree (id);

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (id);

CREATE UNIQUE INDEX pets_pkey ON public.pets USING btree (id);

CREATE UNIQUE INDEX profile_amns_pkey ON public.profile_answers USING btree (id);

CREATE UNIQUE INDEX profile_ethnicities_pkey ON public.profile_ethnicities USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_ethnicity_preferences_pkey ON public.profile_ethnicity_preferences USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_gender_preferences_pkey ON public.profile_gender_preferences USING btree (profile_id);

CREATE UNIQUE INDEX profile_pets_pkey ON public.profile_pets USING btree (profile_id);

CREATE UNIQUE INDEX profile_photos_pkey ON public.profile_photos USING btree (id);

CREATE UNIQUE INDEX profile_pronouns_pkey ON public.profile_pronouns USING btree (profile_id, pronoun_id);

CREATE UNIQUE INDEX "profiles_phoneNumber_key" ON public.profiles USING btree (phone);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX prompts_pkey ON public.prompts USING btree (id);

CREATE UNIQUE INDEX pronouns_pkey ON public.pronouns USING btree (id);

CREATE UNIQUE INDEX sexualities_pkey ON public.sexualities USING btree (id);

CREATE UNIQUE INDEX zodiac_signs_pkey ON public.zodiac_signs USING btree (id);

alter table "public"."children" add constraint "children_pkey" PRIMARY KEY using index "children_pkey";

alter table "public"."covid_vaccine" add constraint "covid_vaccine_pkey" PRIMARY KEY using index "covid_vaccine_pkey";

alter table "public"."ethnicities" add constraint "ethnicities_pkey" PRIMARY KEY using index "ethnicities_pkey";

alter table "public"."family_plans" add constraint "family_plans_pkey" PRIMARY KEY using index "family_plans_pkey";

alter table "public"."genders" add constraint "genders_pkey" PRIMARY KEY using index "genders_pkey";

alter table "public"."interaction_status" add constraint "interaction_status_pkey" PRIMARY KEY using index "interaction_status_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."pets" add constraint "pets_pkey" PRIMARY KEY using index "pets_pkey";

alter table "public"."profile_answers" add constraint "profile_amns_pkey" PRIMARY KEY using index "profile_amns_pkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_pkey" PRIMARY KEY using index "profile_ethnicities_pkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_pkey" PRIMARY KEY using index "profile_ethnicity_preferences_pkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_pkey" PRIMARY KEY using index "profile_gender_preferences_pkey";

alter table "public"."profile_pets" add constraint "profile_pets_pkey" PRIMARY KEY using index "profile_pets_pkey";

alter table "public"."profile_photos" add constraint "profile_photos_pkey" PRIMARY KEY using index "profile_photos_pkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_pkey" PRIMARY KEY using index "profile_pronouns_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."prompts" add constraint "prompts_pkey" PRIMARY KEY using index "prompts_pkey";

alter table "public"."pronouns" add constraint "pronouns_pkey" PRIMARY KEY using index "pronouns_pkey";

alter table "public"."sexualities" add constraint "sexualities_pkey" PRIMARY KEY using index "sexualities_pkey";

alter table "public"."zodiac_signs" add constraint "zodiac_signs_pkey" PRIMARY KEY using index "zodiac_signs_pkey";

alter table "public"."interactions" add constraint "interactions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_actor_id_fkey";

alter table "public"."interactions" add constraint "interactions_answer_id_fkey" FOREIGN KEY (answer_id) REFERENCES profile_answers(id) not valid;

alter table "public"."interactions" validate constraint "interactions_answer_id_fkey";

alter table "public"."interactions" add constraint "interactions_photo_id_fkey" FOREIGN KEY (photo_id) REFERENCES profile_photos(id) not valid;

alter table "public"."interactions" validate constraint "interactions_photo_id_fkey";

alter table "public"."interactions" add constraint "interactions_status_id_fkey" FOREIGN KEY (status_id) REFERENCES interaction_status(id) not valid;

alter table "public"."interactions" validate constraint "interactions_status_id_fkey";

alter table "public"."interactions" add constraint "interactions_target_id_fkey" FOREIGN KEY (target_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_target_id_fkey";

alter table "public"."interactions" add constraint "interactions_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_updated_by_fkey";

alter table "public"."profile_answers" add constraint "profile_amns_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_answers" validate constraint "profile_amns_profile_id_fkey";

alter table "public"."profile_answers" add constraint "profile_amns_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES prompts(id) not valid;

alter table "public"."profile_answers" validate constraint "profile_amns_prompt_id_fkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES ethnicities(id) not valid;

alter table "public"."profile_ethnicities" validate constraint "profile_ethnicities_ethnicity_id_fkey";

alter table "public"."profile_ethnicities" add constraint "profile_ethnicities_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethnicities" validate constraint "profile_ethnicities_profile_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicitiy_preferences_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES ethnicities(id) not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicitiy_preferences_ethnicity_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicitiy_preferences_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicitiy_preferences_profile_id_fkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_gender_id_fkey" FOREIGN KEY (gender_id) REFERENCES genders(id) not valid;

alter table "public"."profile_gender_preferences" validate constraint "profile_gender_preferences_gender_id_fkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_gender_preferences" validate constraint "profile_gender_preferences_profile_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES pets(id) not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_pet_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_profile_id_fkey";

alter table "public"."profile_photos" add constraint "profile_photos_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_photos" validate constraint "profile_photos_profile_id_fkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."profile_pronouns" validate constraint "profile_pronouns_profile_id_fkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_pronoun_id_fkey" FOREIGN KEY (pronoun_id) REFERENCES pronouns(id) not valid;

alter table "public"."profile_pronouns" validate constraint "profile_pronouns_pronoun_id_fkey";

alter table "public"."profiles" add constraint "profiles_children_id_fkey" FOREIGN KEY (children_id) REFERENCES children(id) not valid;

alter table "public"."profiles" validate constraint "profiles_children_id_fkey";

alter table "public"."profiles" add constraint "profiles_covid_vaccine_id_fkey" FOREIGN KEY (covid_vaccine_id) REFERENCES covid_vaccine(id) not valid;

alter table "public"."profiles" validate constraint "profiles_covid_vaccine_id_fkey";

alter table "public"."profiles" add constraint "profiles_family_plan_id_fkey" FOREIGN KEY (family_plan_id) REFERENCES family_plans(id) not valid;

alter table "public"."profiles" validate constraint "profiles_family_plan_id_fkey";

alter table "public"."profiles" add constraint "profiles_gender_id_fkey" FOREIGN KEY (gender_id) REFERENCES genders(id) not valid;

alter table "public"."profiles" validate constraint "profiles_gender_id_fkey";

alter table "public"."profiles" add constraint "profiles_phoneNumber_key" UNIQUE using index "profiles_phoneNumber_key";

alter table "public"."profiles" add constraint "profiles_sexuality_id_fkey" FOREIGN KEY (sexuality_id) REFERENCES sexualities(id) not valid;

alter table "public"."profiles" validate constraint "profiles_sexuality_id_fkey";

alter table "public"."profiles" add constraint "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_zodiac_sign_id_fkey" FOREIGN KEY (zodiac_sign_id) REFERENCES zodiac_signs(id) not valid;

alter table "public"."profiles" validate constraint "profiles_zodiac_sign_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_profile()
 RETURNS TABLE(id uuid, first_name text, last_name text, dob date, height_cm integer, neighborhood text, latitude double precision, longitude double precision, max_distance_km integer, min_age integer, max_age integer, phone text, children jsonb, family_plan jsonb, covid_vaccine jsonb, zodiac_sign jsonb, sexuality jsonb, gender jsonb, ethnicities jsonb, pets jsonb, pronouns jsonb, ethnicity_preferences jsonb, gender_preferences jsonb, answers jsonb, photos jsonb, avatar_url text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare profile_id uuid;
begin
  select profiles.id into profile_id
  from profiles where user_id = auth.uid();

  if profile_id is null then
    raise exception 'profile not found for user %', auth.uid();
  end if;

  return query
  select
    profiles.id,
    profiles.first_name,
    profiles.last_name,
    profiles.dob,
    profiles.height_cm,
    profiles.neighborhood,
    profiles.latitude,
    profiles.longitude,
    profiles.max_distance_km,
    profiles.min_age,
    profiles.max_age,
    profiles.phone,
    row_to_json(children.*)::jsonb as children,
    row_to_json(family_plans.*)::jsonb as family_plan,
    row_to_json(covid_vaccine.*)::jsonb as covid_vaccine,
    row_to_json(zodiac_signs.*)::jsonb as zodiac_sign,
    row_to_json(sexualities.*)::jsonb as sexuality,
    json_build_object('id', genders.id, 'name', genders.name)::jsonb as gender,
    (
      select coalesce(jsonb_agg(ethnicities.*), '[]'::jsonb) 
      from profile_ethnicities
      left join ethnicities on ethnicities.id = profile_ethnicities.ethnicity_id
      where profile_ethnicities.profile_id = profiles.id
    ) as ethnicities,
    (
      select coalesce(jsonb_agg(pets.*), '[]'::jsonb) 
      from profile_pets
      left join pets on pets.id = profile_pets.pet_id
      where profile_pets.profile_id = profiles.id
    ) as pets,
    (
      select coalesce(jsonb_agg(pronouns.*), '[]'::jsonb) 
      from profile_pronouns
      left join pronouns on pronouns.id = profile_pronouns.pronoun_id
      where profile_pronouns.profile_id = profiles.id
    ) as pronouns,
    (
      select coalesce(jsonb_agg(ethnicities.*), '[]'::jsonb) 
      from profile_ethnicity_preferences
      left join ethnicities on ethnicities.id = profile_ethnicity_preferences.ethnicity_id
      where profile_ethnicity_preferences.profile_id = profiles.id
    ) as ethnicity_preferences,
    (
      select coalesce(jsonb_agg(json_build_object('id', genders.id, 'name', genders.plural_name)), '[]'::jsonb) 
      from profile_gender_preferences
      left join genders on genders.id = profile_gender_preferences.gender_id
      where profile_gender_preferences.profile_id = profiles.id
    ) as gender_preferences,
    (
      select coalesce(jsonb_agg(json_build_object(
        'id', profile_answers.id,
        'answer_text', profile_answers.answer_text,
        'answer_order', profile_answers.answer_order,
        'prompt_id', profile_answers.prompt_id,
        'question', prompts.question
      ) order by profile_answers.answer_order), '[]'::jsonb)
      from profile_answers
      left join prompts on prompts.id = profile_answers.prompt_id
      where profile_answers.profile_id = profiles.id and profile_answers.is_active = true
    ) as answers,
    (
      select coalesce(jsonb_agg(json_build_object(
        'id', profile_photos.id,
        'photo_url', profile_photos.photo_url,
        'photo_order', profile_photos.photo_order
      ) order by profile_photos.photo_order), '[]'::jsonb)
      from profile_photos
      where profile_photos.profile_id = profiles.id and profile_photos.is_active = true
    ) as photos,
    (
      select photo_url
      from profile_photos
      where profile_photos.profile_id = profiles.id and profile_photos.is_active = true
      order by profile_photos.photo_order
      limit 1
    ) as avatar_url
    from profiles
    left join children on children.id = profiles.children_id
    left join family_plans on family_plans.id = profiles.family_plan_id
    left join covid_vaccine on covid_vaccine.id = profiles.covid_vaccine_id
    left join zodiac_signs on zodiac_signs.id = profiles.zodiac_sign_id
    left join sexualities on sexualities.id = profiles.sexuality_id
    left join genders on genders.id = profiles.gender_id
    where profiles.id = profile_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles(user_id, phone)
  values (new.id, new.phone)
  on conflict (phone)
  do update set user_id = new.id;
  return new;
end;
$function$
;

grant delete on table "public"."children" to "anon";

grant insert on table "public"."children" to "anon";

grant references on table "public"."children" to "anon";

grant select on table "public"."children" to "anon";

grant trigger on table "public"."children" to "anon";

grant truncate on table "public"."children" to "anon";

grant update on table "public"."children" to "anon";

grant delete on table "public"."children" to "authenticated";

grant insert on table "public"."children" to "authenticated";

grant references on table "public"."children" to "authenticated";

grant select on table "public"."children" to "authenticated";

grant trigger on table "public"."children" to "authenticated";

grant truncate on table "public"."children" to "authenticated";

grant update on table "public"."children" to "authenticated";

grant delete on table "public"."children" to "service_role";

grant insert on table "public"."children" to "service_role";

grant references on table "public"."children" to "service_role";

grant select on table "public"."children" to "service_role";

grant trigger on table "public"."children" to "service_role";

grant truncate on table "public"."children" to "service_role";

grant update on table "public"."children" to "service_role";

grant delete on table "public"."covid_vaccine" to "anon";

grant insert on table "public"."covid_vaccine" to "anon";

grant references on table "public"."covid_vaccine" to "anon";

grant select on table "public"."covid_vaccine" to "anon";

grant trigger on table "public"."covid_vaccine" to "anon";

grant truncate on table "public"."covid_vaccine" to "anon";

grant update on table "public"."covid_vaccine" to "anon";

grant delete on table "public"."covid_vaccine" to "authenticated";

grant insert on table "public"."covid_vaccine" to "authenticated";

grant references on table "public"."covid_vaccine" to "authenticated";

grant select on table "public"."covid_vaccine" to "authenticated";

grant trigger on table "public"."covid_vaccine" to "authenticated";

grant truncate on table "public"."covid_vaccine" to "authenticated";

grant update on table "public"."covid_vaccine" to "authenticated";

grant delete on table "public"."covid_vaccine" to "service_role";

grant insert on table "public"."covid_vaccine" to "service_role";

grant references on table "public"."covid_vaccine" to "service_role";

grant select on table "public"."covid_vaccine" to "service_role";

grant trigger on table "public"."covid_vaccine" to "service_role";

grant truncate on table "public"."covid_vaccine" to "service_role";

grant update on table "public"."covid_vaccine" to "service_role";

grant delete on table "public"."ethnicities" to "anon";

grant insert on table "public"."ethnicities" to "anon";

grant references on table "public"."ethnicities" to "anon";

grant select on table "public"."ethnicities" to "anon";

grant trigger on table "public"."ethnicities" to "anon";

grant truncate on table "public"."ethnicities" to "anon";

grant update on table "public"."ethnicities" to "anon";

grant delete on table "public"."ethnicities" to "authenticated";

grant insert on table "public"."ethnicities" to "authenticated";

grant references on table "public"."ethnicities" to "authenticated";

grant select on table "public"."ethnicities" to "authenticated";

grant trigger on table "public"."ethnicities" to "authenticated";

grant truncate on table "public"."ethnicities" to "authenticated";

grant update on table "public"."ethnicities" to "authenticated";

grant delete on table "public"."ethnicities" to "service_role";

grant insert on table "public"."ethnicities" to "service_role";

grant references on table "public"."ethnicities" to "service_role";

grant select on table "public"."ethnicities" to "service_role";

grant trigger on table "public"."ethnicities" to "service_role";

grant truncate on table "public"."ethnicities" to "service_role";

grant update on table "public"."ethnicities" to "service_role";

grant delete on table "public"."family_plans" to "anon";

grant insert on table "public"."family_plans" to "anon";

grant references on table "public"."family_plans" to "anon";

grant select on table "public"."family_plans" to "anon";

grant trigger on table "public"."family_plans" to "anon";

grant truncate on table "public"."family_plans" to "anon";

grant update on table "public"."family_plans" to "anon";

grant delete on table "public"."family_plans" to "authenticated";

grant insert on table "public"."family_plans" to "authenticated";

grant references on table "public"."family_plans" to "authenticated";

grant select on table "public"."family_plans" to "authenticated";

grant trigger on table "public"."family_plans" to "authenticated";

grant truncate on table "public"."family_plans" to "authenticated";

grant update on table "public"."family_plans" to "authenticated";

grant delete on table "public"."family_plans" to "service_role";

grant insert on table "public"."family_plans" to "service_role";

grant references on table "public"."family_plans" to "service_role";

grant select on table "public"."family_plans" to "service_role";

grant trigger on table "public"."family_plans" to "service_role";

grant truncate on table "public"."family_plans" to "service_role";

grant update on table "public"."family_plans" to "service_role";

grant delete on table "public"."genders" to "anon";

grant insert on table "public"."genders" to "anon";

grant references on table "public"."genders" to "anon";

grant select on table "public"."genders" to "anon";

grant trigger on table "public"."genders" to "anon";

grant truncate on table "public"."genders" to "anon";

grant update on table "public"."genders" to "anon";

grant delete on table "public"."genders" to "authenticated";

grant insert on table "public"."genders" to "authenticated";

grant references on table "public"."genders" to "authenticated";

grant select on table "public"."genders" to "authenticated";

grant trigger on table "public"."genders" to "authenticated";

grant truncate on table "public"."genders" to "authenticated";

grant update on table "public"."genders" to "authenticated";

grant delete on table "public"."genders" to "service_role";

grant insert on table "public"."genders" to "service_role";

grant references on table "public"."genders" to "service_role";

grant select on table "public"."genders" to "service_role";

grant trigger on table "public"."genders" to "service_role";

grant truncate on table "public"."genders" to "service_role";

grant update on table "public"."genders" to "service_role";

grant delete on table "public"."interaction_status" to "anon";

grant insert on table "public"."interaction_status" to "anon";

grant references on table "public"."interaction_status" to "anon";

grant select on table "public"."interaction_status" to "anon";

grant trigger on table "public"."interaction_status" to "anon";

grant truncate on table "public"."interaction_status" to "anon";

grant update on table "public"."interaction_status" to "anon";

grant delete on table "public"."interaction_status" to "authenticated";

grant insert on table "public"."interaction_status" to "authenticated";

grant references on table "public"."interaction_status" to "authenticated";

grant select on table "public"."interaction_status" to "authenticated";

grant trigger on table "public"."interaction_status" to "authenticated";

grant truncate on table "public"."interaction_status" to "authenticated";

grant update on table "public"."interaction_status" to "authenticated";

grant delete on table "public"."interaction_status" to "service_role";

grant insert on table "public"."interaction_status" to "service_role";

grant references on table "public"."interaction_status" to "service_role";

grant select on table "public"."interaction_status" to "service_role";

grant trigger on table "public"."interaction_status" to "service_role";

grant truncate on table "public"."interaction_status" to "service_role";

grant update on table "public"."interaction_status" to "service_role";

grant delete on table "public"."interactions" to "anon";

grant insert on table "public"."interactions" to "anon";

grant references on table "public"."interactions" to "anon";

grant select on table "public"."interactions" to "anon";

grant trigger on table "public"."interactions" to "anon";

grant truncate on table "public"."interactions" to "anon";

grant update on table "public"."interactions" to "anon";

grant delete on table "public"."interactions" to "authenticated";

grant insert on table "public"."interactions" to "authenticated";

grant references on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant trigger on table "public"."interactions" to "authenticated";

grant truncate on table "public"."interactions" to "authenticated";

grant update on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";

grant delete on table "public"."pets" to "anon";

grant insert on table "public"."pets" to "anon";

grant references on table "public"."pets" to "anon";

grant select on table "public"."pets" to "anon";

grant trigger on table "public"."pets" to "anon";

grant truncate on table "public"."pets" to "anon";

grant update on table "public"."pets" to "anon";

grant delete on table "public"."pets" to "authenticated";

grant insert on table "public"."pets" to "authenticated";

grant references on table "public"."pets" to "authenticated";

grant select on table "public"."pets" to "authenticated";

grant trigger on table "public"."pets" to "authenticated";

grant truncate on table "public"."pets" to "authenticated";

grant update on table "public"."pets" to "authenticated";

grant delete on table "public"."pets" to "service_role";

grant insert on table "public"."pets" to "service_role";

grant references on table "public"."pets" to "service_role";

grant select on table "public"."pets" to "service_role";

grant trigger on table "public"."pets" to "service_role";

grant truncate on table "public"."pets" to "service_role";

grant update on table "public"."pets" to "service_role";

grant delete on table "public"."profile_answers" to "anon";

grant insert on table "public"."profile_answers" to "anon";

grant references on table "public"."profile_answers" to "anon";

grant select on table "public"."profile_answers" to "anon";

grant trigger on table "public"."profile_answers" to "anon";

grant truncate on table "public"."profile_answers" to "anon";

grant update on table "public"."profile_answers" to "anon";

grant delete on table "public"."profile_answers" to "authenticated";

grant insert on table "public"."profile_answers" to "authenticated";

grant references on table "public"."profile_answers" to "authenticated";

grant select on table "public"."profile_answers" to "authenticated";

grant trigger on table "public"."profile_answers" to "authenticated";

grant truncate on table "public"."profile_answers" to "authenticated";

grant update on table "public"."profile_answers" to "authenticated";

grant delete on table "public"."profile_answers" to "service_role";

grant insert on table "public"."profile_answers" to "service_role";

grant references on table "public"."profile_answers" to "service_role";

grant select on table "public"."profile_answers" to "service_role";

grant trigger on table "public"."profile_answers" to "service_role";

grant truncate on table "public"."profile_answers" to "service_role";

grant update on table "public"."profile_answers" to "service_role";

grant delete on table "public"."profile_ethnicities" to "anon";

grant insert on table "public"."profile_ethnicities" to "anon";

grant references on table "public"."profile_ethnicities" to "anon";

grant select on table "public"."profile_ethnicities" to "anon";

grant trigger on table "public"."profile_ethnicities" to "anon";

grant truncate on table "public"."profile_ethnicities" to "anon";

grant update on table "public"."profile_ethnicities" to "anon";

grant delete on table "public"."profile_ethnicities" to "authenticated";

grant insert on table "public"."profile_ethnicities" to "authenticated";

grant references on table "public"."profile_ethnicities" to "authenticated";

grant select on table "public"."profile_ethnicities" to "authenticated";

grant trigger on table "public"."profile_ethnicities" to "authenticated";

grant truncate on table "public"."profile_ethnicities" to "authenticated";

grant update on table "public"."profile_ethnicities" to "authenticated";

grant delete on table "public"."profile_ethnicities" to "service_role";

grant insert on table "public"."profile_ethnicities" to "service_role";

grant references on table "public"."profile_ethnicities" to "service_role";

grant select on table "public"."profile_ethnicities" to "service_role";

grant trigger on table "public"."profile_ethnicities" to "service_role";

grant truncate on table "public"."profile_ethnicities" to "service_role";

grant update on table "public"."profile_ethnicities" to "service_role";

grant delete on table "public"."profile_ethnicity_preferences" to "anon";

grant insert on table "public"."profile_ethnicity_preferences" to "anon";

grant references on table "public"."profile_ethnicity_preferences" to "anon";

grant select on table "public"."profile_ethnicity_preferences" to "anon";

grant trigger on table "public"."profile_ethnicity_preferences" to "anon";

grant truncate on table "public"."profile_ethnicity_preferences" to "anon";

grant update on table "public"."profile_ethnicity_preferences" to "anon";

grant delete on table "public"."profile_ethnicity_preferences" to "authenticated";

grant insert on table "public"."profile_ethnicity_preferences" to "authenticated";

grant references on table "public"."profile_ethnicity_preferences" to "authenticated";

grant select on table "public"."profile_ethnicity_preferences" to "authenticated";

grant trigger on table "public"."profile_ethnicity_preferences" to "authenticated";

grant truncate on table "public"."profile_ethnicity_preferences" to "authenticated";

grant update on table "public"."profile_ethnicity_preferences" to "authenticated";

grant delete on table "public"."profile_ethnicity_preferences" to "service_role";

grant insert on table "public"."profile_ethnicity_preferences" to "service_role";

grant references on table "public"."profile_ethnicity_preferences" to "service_role";

grant select on table "public"."profile_ethnicity_preferences" to "service_role";

grant trigger on table "public"."profile_ethnicity_preferences" to "service_role";

grant truncate on table "public"."profile_ethnicity_preferences" to "service_role";

grant update on table "public"."profile_ethnicity_preferences" to "service_role";

grant delete on table "public"."profile_gender_preferences" to "anon";

grant insert on table "public"."profile_gender_preferences" to "anon";

grant references on table "public"."profile_gender_preferences" to "anon";

grant select on table "public"."profile_gender_preferences" to "anon";

grant trigger on table "public"."profile_gender_preferences" to "anon";

grant truncate on table "public"."profile_gender_preferences" to "anon";

grant update on table "public"."profile_gender_preferences" to "anon";

grant delete on table "public"."profile_gender_preferences" to "authenticated";

grant insert on table "public"."profile_gender_preferences" to "authenticated";

grant references on table "public"."profile_gender_preferences" to "authenticated";

grant select on table "public"."profile_gender_preferences" to "authenticated";

grant trigger on table "public"."profile_gender_preferences" to "authenticated";

grant truncate on table "public"."profile_gender_preferences" to "authenticated";

grant update on table "public"."profile_gender_preferences" to "authenticated";

grant delete on table "public"."profile_gender_preferences" to "service_role";

grant insert on table "public"."profile_gender_preferences" to "service_role";

grant references on table "public"."profile_gender_preferences" to "service_role";

grant select on table "public"."profile_gender_preferences" to "service_role";

grant trigger on table "public"."profile_gender_preferences" to "service_role";

grant truncate on table "public"."profile_gender_preferences" to "service_role";

grant update on table "public"."profile_gender_preferences" to "service_role";

grant delete on table "public"."profile_pets" to "anon";

grant insert on table "public"."profile_pets" to "anon";

grant references on table "public"."profile_pets" to "anon";

grant select on table "public"."profile_pets" to "anon";

grant trigger on table "public"."profile_pets" to "anon";

grant truncate on table "public"."profile_pets" to "anon";

grant update on table "public"."profile_pets" to "anon";

grant delete on table "public"."profile_pets" to "authenticated";

grant insert on table "public"."profile_pets" to "authenticated";

grant references on table "public"."profile_pets" to "authenticated";

grant select on table "public"."profile_pets" to "authenticated";

grant trigger on table "public"."profile_pets" to "authenticated";

grant truncate on table "public"."profile_pets" to "authenticated";

grant update on table "public"."profile_pets" to "authenticated";

grant delete on table "public"."profile_pets" to "service_role";

grant insert on table "public"."profile_pets" to "service_role";

grant references on table "public"."profile_pets" to "service_role";

grant select on table "public"."profile_pets" to "service_role";

grant trigger on table "public"."profile_pets" to "service_role";

grant truncate on table "public"."profile_pets" to "service_role";

grant update on table "public"."profile_pets" to "service_role";

grant delete on table "public"."profile_photos" to "anon";

grant insert on table "public"."profile_photos" to "anon";

grant references on table "public"."profile_photos" to "anon";

grant select on table "public"."profile_photos" to "anon";

grant trigger on table "public"."profile_photos" to "anon";

grant truncate on table "public"."profile_photos" to "anon";

grant update on table "public"."profile_photos" to "anon";

grant delete on table "public"."profile_photos" to "authenticated";

grant insert on table "public"."profile_photos" to "authenticated";

grant references on table "public"."profile_photos" to "authenticated";

grant select on table "public"."profile_photos" to "authenticated";

grant trigger on table "public"."profile_photos" to "authenticated";

grant truncate on table "public"."profile_photos" to "authenticated";

grant update on table "public"."profile_photos" to "authenticated";

grant delete on table "public"."profile_photos" to "service_role";

grant insert on table "public"."profile_photos" to "service_role";

grant references on table "public"."profile_photos" to "service_role";

grant select on table "public"."profile_photos" to "service_role";

grant trigger on table "public"."profile_photos" to "service_role";

grant truncate on table "public"."profile_photos" to "service_role";

grant update on table "public"."profile_photos" to "service_role";

grant delete on table "public"."profile_pronouns" to "anon";

grant insert on table "public"."profile_pronouns" to "anon";

grant references on table "public"."profile_pronouns" to "anon";

grant select on table "public"."profile_pronouns" to "anon";

grant trigger on table "public"."profile_pronouns" to "anon";

grant truncate on table "public"."profile_pronouns" to "anon";

grant update on table "public"."profile_pronouns" to "anon";

grant delete on table "public"."profile_pronouns" to "authenticated";

grant insert on table "public"."profile_pronouns" to "authenticated";

grant references on table "public"."profile_pronouns" to "authenticated";

grant select on table "public"."profile_pronouns" to "authenticated";

grant trigger on table "public"."profile_pronouns" to "authenticated";

grant truncate on table "public"."profile_pronouns" to "authenticated";

grant update on table "public"."profile_pronouns" to "authenticated";

grant delete on table "public"."profile_pronouns" to "service_role";

grant insert on table "public"."profile_pronouns" to "service_role";

grant references on table "public"."profile_pronouns" to "service_role";

grant select on table "public"."profile_pronouns" to "service_role";

grant trigger on table "public"."profile_pronouns" to "service_role";

grant truncate on table "public"."profile_pronouns" to "service_role";

grant update on table "public"."profile_pronouns" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."prompts" to "anon";

grant insert on table "public"."prompts" to "anon";

grant references on table "public"."prompts" to "anon";

grant select on table "public"."prompts" to "anon";

grant trigger on table "public"."prompts" to "anon";

grant truncate on table "public"."prompts" to "anon";

grant update on table "public"."prompts" to "anon";

grant delete on table "public"."prompts" to "authenticated";

grant insert on table "public"."prompts" to "authenticated";

grant references on table "public"."prompts" to "authenticated";

grant select on table "public"."prompts" to "authenticated";

grant trigger on table "public"."prompts" to "authenticated";

grant truncate on table "public"."prompts" to "authenticated";

grant update on table "public"."prompts" to "authenticated";

grant delete on table "public"."prompts" to "service_role";

grant insert on table "public"."prompts" to "service_role";

grant references on table "public"."prompts" to "service_role";

grant select on table "public"."prompts" to "service_role";

grant trigger on table "public"."prompts" to "service_role";

grant truncate on table "public"."prompts" to "service_role";

grant update on table "public"."prompts" to "service_role";

grant delete on table "public"."pronouns" to "anon";

grant insert on table "public"."pronouns" to "anon";

grant references on table "public"."pronouns" to "anon";

grant select on table "public"."pronouns" to "anon";

grant trigger on table "public"."pronouns" to "anon";

grant truncate on table "public"."pronouns" to "anon";

grant update on table "public"."pronouns" to "anon";

grant delete on table "public"."pronouns" to "authenticated";

grant insert on table "public"."pronouns" to "authenticated";

grant references on table "public"."pronouns" to "authenticated";

grant select on table "public"."pronouns" to "authenticated";

grant trigger on table "public"."pronouns" to "authenticated";

grant truncate on table "public"."pronouns" to "authenticated";

grant update on table "public"."pronouns" to "authenticated";

grant delete on table "public"."pronouns" to "service_role";

grant insert on table "public"."pronouns" to "service_role";

grant references on table "public"."pronouns" to "service_role";

grant select on table "public"."pronouns" to "service_role";

grant trigger on table "public"."pronouns" to "service_role";

grant truncate on table "public"."pronouns" to "service_role";

grant update on table "public"."pronouns" to "service_role";

grant delete on table "public"."sexualities" to "anon";

grant insert on table "public"."sexualities" to "anon";

grant references on table "public"."sexualities" to "anon";

grant select on table "public"."sexualities" to "anon";

grant trigger on table "public"."sexualities" to "anon";

grant truncate on table "public"."sexualities" to "anon";

grant update on table "public"."sexualities" to "anon";

grant delete on table "public"."sexualities" to "authenticated";

grant insert on table "public"."sexualities" to "authenticated";

grant references on table "public"."sexualities" to "authenticated";

grant select on table "public"."sexualities" to "authenticated";

grant trigger on table "public"."sexualities" to "authenticated";

grant truncate on table "public"."sexualities" to "authenticated";

grant update on table "public"."sexualities" to "authenticated";

grant delete on table "public"."sexualities" to "service_role";

grant insert on table "public"."sexualities" to "service_role";

grant references on table "public"."sexualities" to "service_role";

grant select on table "public"."sexualities" to "service_role";

grant trigger on table "public"."sexualities" to "service_role";

grant truncate on table "public"."sexualities" to "service_role";

grant update on table "public"."sexualities" to "service_role";

grant delete on table "public"."zodiac_signs" to "anon";

grant insert on table "public"."zodiac_signs" to "anon";

grant references on table "public"."zodiac_signs" to "anon";

grant select on table "public"."zodiac_signs" to "anon";

grant trigger on table "public"."zodiac_signs" to "anon";

grant truncate on table "public"."zodiac_signs" to "anon";

grant update on table "public"."zodiac_signs" to "anon";

grant delete on table "public"."zodiac_signs" to "authenticated";

grant insert on table "public"."zodiac_signs" to "authenticated";

grant references on table "public"."zodiac_signs" to "authenticated";

grant select on table "public"."zodiac_signs" to "authenticated";

grant trigger on table "public"."zodiac_signs" to "authenticated";

grant truncate on table "public"."zodiac_signs" to "authenticated";

grant update on table "public"."zodiac_signs" to "authenticated";

grant delete on table "public"."zodiac_signs" to "service_role";

grant insert on table "public"."zodiac_signs" to "service_role";

grant references on table "public"."zodiac_signs" to "service_role";

grant select on table "public"."zodiac_signs" to "service_role";

grant trigger on table "public"."zodiac_signs" to "service_role";

grant truncate on table "public"."zodiac_signs" to "service_role";

grant update on table "public"."zodiac_signs" to "service_role";


